---
collections:
  - name: ahaydon.hyperv
    type: git
    version: main
    source: https://github.com/ahaydon/ansible-hyperv-collection

  - name: qlik.qlikview
    type: git
    version: main
    source: https://github.com/QlikProfessionalServices/ansible-qlikview-collection

  - name: community.general
  - name: community.windows
